# Set the path to your whisper.cpp directory and model file.
export WHISPER_CPP_DIR="/Users/bettyhuang/myapps/whisper.cpp"
export WHISPER_MODEL="ggml-large-v3-turbo-q8_0"
export LLAMA_CLI="/opt/homebrew/bin/llama-completion"
export LLAMA_MODEL_PATH="/Users/bettyhuang/llm_models/Qwen3.5-4B-UD-Q4_K_XL.gguf"
export MLX_WHISPER_MODEL="/Users/bettyhuang/myapps/tool-transcribe/models/whisper-large-v3-turbo-8bit"
# Whisper models:
# tiny
# tiny.en
# tiny-q5_1
# tiny.en-q5_1
# tiny-q8_0
# base
# base.en
# base-q5_1
# base.en-q5_1
# base-q8_0
# small
# small.en
# small.en-tdrz
# small-q5_1
# small.en-q5_1
# small-q8_0
# medium
# medium.en
# medium-q5_0
# medium.en-q5_0
# medium-q8_0
# large-v1
# large-v2
# large-v2-q5_0
# large-v2-q8_0
# large-v3
# large-v3-q5_0
# large-v3-turbo
# large-v3-turbo-q5_0
# large-v3-turbo-q8_0
